# Generated by Django 5.0.3 on 2024-03-19 02:17

import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('notification_opted_in', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='Admin', max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Admin', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'customers',
            },
        ),
        migrations.CreateModel(
            name='PackageCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='Admin', max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Admin', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'package categories',
            },
        ),
        migrations.CreateModel(
            name='PackageStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='Admin', max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Admin', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'package statuses',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, null=True, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=255, null=True)),
                ('date_delivered', models.DateField(null=True)),
                ('date_shipped', models.DateField(null=True)),
                ('expected_delivery_date', models.DateField(null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('length', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.CharField(default='Admin', max_length=255)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('updated_by', models.CharField(default='Admin', max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.customer')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.packagecategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backendapp.packagestatus')),
            ],
            options={
                'verbose_name_plural': 'packages',
            },
        ),
    ]
